{{- if .Values.controller.enabled }}
{{ $tls := fromYaml (include "everestController.tlsCerts" .) }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: everest-controller-validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: {{ index $tls "ca.crt" }}
    service:
      name: everest-controller-webhook-service
      namespace: {{ include "everest.namespace" . }}
      path: /validate-monitoring-openeverest-io-v1alpha1-monitoringconfig
  failurePolicy: Fail
  name: vmonitoringconfig-v1alpha1.monitoring.openeverest.io
  rules:
  - apiGroups:
    - monitoring.openeverest.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - monitoringconfigs
  sideEffects: None
---
apiVersion: v1
kind: Secret
metadata:
  name: everest-controller-webhook-server-cert
  namespace: {{ include "everest.namespace" . }}
type: kubernetes.io/tls
data:
  {{- range $key, $value := $tls }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
