name: Everest Chart Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Everest version"
        required: true
      branch:
        required: false
        default: main
        description: "Branch to checkout for chart release"

permissions:
  contents: write

jobs:
  release:
    env:
      VERSION: ${{ github.event.inputs.version }}
      # Is set if the VERSION corresponds to an RC.
      IS_RC: 0
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variables
        run: |
          if [[ ! $VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "IS_RC=1" >> $GITHUB_ENV
          fi

      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          ref: ${{ github.event.inputs.branch }}
          sparse-checkout: |
            charts/everest

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Prepare RC
        if: ${{ env.IS_RC == '1' }}
        run: |
          cd charts/everest
          make release-dev

      - name: Prepare release
        if: ${{ env.IS_RC == '0' }}
        run: |
          cd charts/everest
          make release

      - name: Install Helm
        uses: azure/setup-helm@18bc76811624f360dbd7f18c2d4ecb32c7b87bab # v1.1
        with:
          version: v3.4.0

      - name: Release chart
        uses: helm/chart-releaser-action@a917fd15b20e8b64b94d9158ad54cd6345335584 # v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Release sub-chart
        uses: helm/chart-releaser-action@a917fd15b20e8b64b94d9158ad54cd6345335584 # v1.6.0
        with:
          charts_dir: charts/everest/charts
          skip_existing: true
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
